# Generated by Django 5.1.4 on 2025-11-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_devicetoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
