# Generated by Django 5.1.4 on 2025-11-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='address',
            name='town_city',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='akola', max_length=60),
            preserve_default=False,
        ),
    ]
