# Generated by Django 5.1.4 on 2025-11-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_address_pincode_remove_address_town_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('intransit', 'In Transit'), ('delivered', 'Delivered'), ('delivery_boy_assigned', 'delivery_boy_assigned'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('returned_by_customer', 'returned_by_customer'), ('returned_by_vendor', 'returned_by_vendor'), ('approved_by_customer', 'approved_by_customer'), ('cancelled_by_vendor', 'cancelled_by_vendor'), ('cancelled_by_customer', 'cancelled_by_customer')], default='pending', max_length=28),
        ),
    ]
