# Generated by Django 5.1.4 on 2026-01-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_reellike_reelcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trial_begins_at',
            field=models.DateTimeField(blank=True, help_text='Set when customer verifies trial OTP (trial begin)', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='Set when customer ends trial (trial ended)', null=True),
        ),
    ]
