# Generated by Django 5.1.4 on 2026-02-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('ordered', 'Ordered'), ('cancelled', 'Cancelled'), ('cancelled_by_customer', 'Cancelled by Customer'), ('cancelled_by_vendor', 'Cancelled by Vendor'), ('delivery_boy_assigned', 'Delivery Boy Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('returned_by_vendor', 'Returned by Vendor'), ('returned/replaced_rejected', 'Return/Replace Rejected'), ('returned/replaced_completed', 'Return/Replace Completed'), ('replace', 'Replace')], default='trial', max_length=28),
        ),
    ]
