# Generated by Django 5.1.4 on 2026-02-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_update_orderitem_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('ordered', 'Ordered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('replace', 'Replace')], default='trial', max_length=28),
        ),
    ]
