# Generated by Django 5.1.4 on 2026-02-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_simplify_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_color_looks_different',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_material_quality_not_expected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_other_reason',
            field=models.TextField(blank=True, help_text="Text reason when 'other' is selected", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_size_doesnt_fit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_style_doesnt_suit',
            field=models.BooleanField(default=False),
        ),
    ]
