# Generated by Django 5.1.4 on 2026-02-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_add_order_cancellation_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('ordered', 'Ordered'), ('cancelled', 'Cancelled'), ('delivery_boy_assigned', 'Delivery Boy Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('replace', 'Replace')], default='trial', max_length=28),
        ),
    ]
