# Generated by Django 5.1.4 on 2026-02-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_orderitem_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ready_to_dispatch', 'Ready to Dispatch'), ('not_accepted', 'Not Accepted'), ('accepted', 'Accepted'), ('in_transit', 'In Transit'), ('trial_begin', 'Trial Begin'), ('trial_ended', 'Trial Ended'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='not_accepted', max_length=20),
        ),
    ]
