# Generated by Django 5.1.4 on 2026-02-13 15:12

from django.db import migrations, models


def migrate_returned_replace_to_cancelled(apps, schema_editor):
    """Update any OrderItem with status 'returned' or 'replace' to 'cancelled'."""
    OrderItem = apps.get_model('customer', 'OrderItem')
    OrderItem.objects.filter(status__in=['returned', 'replace']).update(status='cancelled')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_add_review_photo'),
    ]

    operations = [
        migrations.RunPython(migrate_returned_replace_to_cancelled, noop),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('ordered', 'Ordered'), ('cancelled', 'Cancelled')], default='trial', max_length=28),
        ),
    ]
