# Generated by Django 5.1.4 on 2026-02-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_remove_returned_replace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='cod, cashfree, razorpay', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Cashfree cf_payment_id / transaction id', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, help_text='upi, card, netbanking, wallet', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, help_text='pending, success, failed, refunded', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pg_order_id',
            field=models.CharField(blank=True, help_text='Cashfree cf_order_id / Razorpay order id', max_length=100, null=True),
        ),
    ]
