# Generated by Django 5.1.4 on 2026-04-02 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_add_payment_gateway_fields'),
        ('vendor', '0027_deliveryboy_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favourite',
            index=models.Index(fields=['user', 'created_at'], name='customer_fa_user_id_c1fccd_idx'),
        ),
        migrations.AddIndex(
            model_name='favourite',
            index=models.Index(fields=['product', 'created_at'], name='customer_fa_product_e848b5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='customer_or_user_id_64f04e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_boy', 'created_at'], name='customer_or_deliver_7e432e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='customer_or_status_99d37a_idx'),
        ),
    ]
