# Generated by Django 5.1.4 on 2026-04-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_favourite_customer_fa_user_id_c1fccd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ready_to_dispatch', 'Ready to Dispatch'), ('not_accepted', 'Not Accepted'), ('accepted', 'Accepted'), ('in_transit', 'In Transit'), ('reached', 'Reached'), ('trial_begin', 'Trial Begin'), ('trial_ended', 'Trial Ended'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='not_accepted', max_length=20),
        ),
    ]
