# Generated by Django 5.1.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_city_delete_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategory',
            name='categories',
        ),
        migrations.AddField(
            model_name='product_category',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='masters.maincategory'),
        ),
    ]
