# Generated by Django 5.1.4 on 2026-01-30 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_add_notification_campaign'),
        ('vendor', '0004_rename_erial_numbers_product_serial_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='start_time',
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='notifications/banners/'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag - campaigns marked as deleted still count toward monthly limit'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_campaigns', to='vendor.product'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='redirect_to',
            field=models.CharField(choices=[('store', 'Store'), ('product', 'Product'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_campaigns', to='vendor.vendor_store'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='description',
            field=models.CharField(blank=True, default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('ended', 'Ended'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
